name: ladytabtab
description: A beauty app - Lady Tabtab.

publish_to: "none"

version: 2.0.1+15
#version >> 1.0.4 + 8 = 1.0.4
#version >> 1.0.5 + 9 = 1.0.5 01/04/2022
#version >> 1.0.6 + 10 = 1.0.6 19/04/2022
#version >> 1.0.7 + 11 = 1.0.7 26/04/2022
#version >> 1.0.8 + 12 = 1.0.8 27/04/2022
#version >> 1.0.9 + 13 = 1.0.9 11/05/2022
#version >> 1.0.10 + 14 = 1.0.10 11/05/2022
#version >> 2.0.1 + 15 = 2.0.1 15/05/2022

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl:

  # flutter_feather_icons:

  # DATABASE - FIREBASE
  firebase_core:
  firebase_auth:
  firebase_storage:
  cloud_firestore:
  firebase_messaging:
  # flutterfire_ui:

  crypto:

  flutter_local_notifications:
  google_sign_in:
  # google_fonts:
  flutter_facebook_auth: ^4.3.4

  # Animations
  # animations:
  carousel_slider:

  # flutter_staggered_grid_view: ^0.4.1
  path:
  cached_network_image:
  flutter_svg:
  shared_preferences:

  bloc: ^8.0.3
  flutter_bloc: ^8.0.1

  pin_code_fields:

  #Internet connection
  connectivity_plus:
  internet_connection_checker:

  # shimmer:
  image_picker:
  # permission_handler:
  # lottie:
  url_launcher:
  # rxdart:
  # timelines:
  fluttertoast:
  # google_maps_flutter:
  # location:
  sign_in_with_apple:
  # shimmr:

  # geocoding:
  # geolocator:
  algolia:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat.ttf
    - family: TheSans
      fonts:
        - asset: assets/fonts/TheSansPlain.otf
    - family: Janna
      fonts:
        - asset: assets/fonts/janna/JannaLT-Regular.ttf
        - asset: assets/fonts/janna/JannaLT-Bold.ttf
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai-Regular.ttf

  assets:
    - assets/images/onboarding/onBoarding.jpeg
    - assets/images/onboarding/slider.png
    - assets/images/svg/
    - assets/animation/
    - assets/images/
    - assets/images/ic_lady.png

    # Language
    - assets/i18n/en.json
    - assets/i18n/ar.json
